name: Windows-Qt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'

      - name: Install dependencies
        run: choco install cmake ninja -y

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          ninja
